version: '3.4'

services:
  player:
    image: ghcr.io/software-driven/testappplayerserver:1.0.0
    volumes:
      - ./TestApp.Player/Logins:/app/data
      - ./TestApp.Player/Results:/app/results
      - ./TestApp.Player/Content:/app/Content
      - type: bind
        source: ./TestApp.Player/appsettings.json
        target: /app/appsettings.json
  editor:
    image: ghcr.io/software-driven/testappeditorserver:1.0.0
    volumes:
      - ./TestApp.Editor/Data:/app/data
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - player
      - editor
    restart: always