version: '3.4'

services:
  testapp.player:
    image: ghcr.io/software-driven/testappplayerserver:preview
    ports:
      - 8001:80
    volumes:
      - ./TestApp.Player/Logins:/app/data
      - ./TestApp.Player/Results:/app/results
      - ./TestApp.Player/Content:/app/Content
      - type: bind
        source: ./TestApp.Player/appsettings.json
        target: /app/appsettings.json
  testapp.editor:
    image: ghcr.io/software-driven/testappeditorserver:preview
    ports:
      - 8002:80
    volumes:
      - ./TestApp.Editor/Data:/app/data


